<a href="https://colab.research.google.com/github/Pepcoders/Data-Science-March/blob/main/NLP/FakeNewsClassifier_March.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#############DATASET LINK ########
#######. https://drive.google.com/file/d/19FoplQJJWGdxPi88mB8-jOBxJDmZs58h/view?usp=sharing

In [1]:
import nltk
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/basque_grammars.zip.
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/biocreative_ppi.zip.
[nltk_data]    | Downloadin

True

In [2]:
import pandas as pd


In [3]:
df=pd.read_csv('/content/drive/MyDrive/fake-news/fake_train.csv')

In [4]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      20800 non-null  int64 
 1   title   20242 non-null  object
 2   author  18843 non-null  object
 3   text    20761 non-null  object
 4   label   20800 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 812.6+ KB


In [6]:
df.isna().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [7]:
df=df.dropna()

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18285 entries, 0 to 20799
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      18285 non-null  int64 
 1   title   18285 non-null  object
 2   author  18285 non-null  object
 3   text    18285 non-null  object
 4   label   18285 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 857.1+ KB


In [9]:
X=df.drop(['label'],axis=1)

In [10]:
y=df['label']

In [11]:
import tensorflow as tf

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM,
from tensorflow.keras.layers import Dense

In [12]:
voc_size=5000

In [14]:
messages=X.copy()

messages.reset_index(drop=True,inplace=True)

In [17]:
messages=messages.drop(['id'],axis=1)

In [18]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [20]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [21]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[502, 2805, 436, 3266, 67, 761, 3525, 888, 4095, 2207],
 [378, 4163, 2666, 1317, 1933, 636, 2999],
 [230, 4503, 214, 3355],
 [3087, 4168, 730, 3785, 72, 986],
 [4526, 1933, 3805, 975, 4284, 4585, 1933, 3122, 2717, 951],
 [185,
  3459,
  2219,
  537,
  3102,
  2424,
  1572,
  2664,
  3914,
  1034,
  4697,
  1497,
  3551,
  4160,
  2999],
 [1453, 3046, 3081, 4429, 1685, 143, 1202, 389, 1360, 3460, 3194],
 [384, 4472, 2411, 233, 2859, 1617, 2424, 3330, 1360, 3460, 3194],
 [235, 3036, 3435, 2931, 4443, 1943, 594, 2727, 2424, 2246],
 [1140, 1441, 3394, 2806, 1722, 3515, 1750, 3466],
 [3183, 4804, 717, 2399, 278, 1132, 957, 4349, 4365, 3539, 3876],
 [3785, 2237, 67, 1943, 2424, 2859],
 [1055, 1639, 709, 1450, 315, 3215, 502, 2518, 3273],
 [3345, 2323, 934, 1983, 1538, 4936, 1353, 1360, 3460, 3194],
 [4721, 4973, 3305, 3857, 2754, 1360, 3460, 3194],
 [3897, 2471, 4101, 96, 426, 4857, 1306, 2700, 2502, 1743],
 [971, 2650, 4163],
 [2129, 2330, 4524, 204, 2424, 2180, 4508, 2999],
 [1918, 1449, 

In [22]:
sent_length=20

In [23]:
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...  888 4095 2207]
 [   0    0    0 ... 1933  636 2999]
 [   0    0    0 ... 4503  214 3355]
 ...
 [   0    0    0 ... 1360 3460 3194]
 [   0    0    0 ... 4438  752 2814]
 [   0    0    0 ... 3602 1078 1577]]


In [26]:
from tensorflow.keras.layers import Dropout

embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.4))
#model.add(LSTM(50))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 20, 40)            200000    
                                                                 
 dropout_4 (Dropout)         (None, 20, 40)            0         
                                                                 
 lstm_3 (LSTM)               (None, 100)               56400     
                                                                 
 dropout_5 (Dropout)         (None, 100)               0         
                                                                 
 dense_1 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [27]:
len(embedded_docs),y.shape

(18285, (18285,))

In [28]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_final,y_final,random_state=42,test_size=0.2)

In [ ]:
model.fit(X_train,y_train,epochs=20,batch_size=64,validation_data=(X_test,y_test))

Epoch 1/20
229/229 [==============================] - 18s 56ms/step - loss: 0.3230 - accuracy: 0.8471 - val_loss: 0.2098 - val_accuracy: 0.9114
Epoch 2/20
229/229 [==============================] - 14s 60ms/step - loss: 0.1456 - accuracy: 0.9441 - val_loss: 0.2077 - val_accuracy: 0.9174
Epoch 3/20
229/229 [==============================] - 12s 53ms/step - loss: 0.1121 - accuracy: 0.9588 - val_loss: 0.2375 - val_accuracy: 0.9032
Epoch 4/20
229/229 [==============================] - 13s 55ms/step - loss: 0.0925 - accuracy: 0.9660 - val_loss: 0.2612 - val_accuracy: 0.9111
Epoch 5/20
229/229 [==============================] - 14s 62ms/step - loss: 0.0783 - accuracy: 0.9721 - val_loss: 0.2669 - val_accuracy: 0.9117
Epoch 6/20
229/229 [==============================] - 12s 54ms/step - loss: 0.0683 - accuracy: 0.9768 - val_loss: 0.3425 - val_accuracy: 0.9092
Epoch 7/20
229/229 [==============================] - 13s 56ms/step - loss: 0.0524 - accuracy: 0.9818 - val_loss: 0.3784 - val_accuracy: