<a href="https://colab.research.google.com/github/Pepcoders/Data-Science-March/blob/main/ANN/ANN_March.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Tensorflow Basics***

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.8.2


In [3]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


True

In [4]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [5]:
k=tf.constant(42)

In [6]:
k

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [7]:
a=tf.constant([[4,2],[9,5]])

In [8]:
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 2],
       [9, 5]], dtype=int32)>

In [9]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [10]:
print(tf.zeros(shape=(2,3)))

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [11]:
a1 = tf.constant([[3,4,5], [3,4,5]])
a2= tf.constant([[1,2,3], [1,2,3]])

c=tf.add(a1,a2)

In [12]:
c

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 6, 8],
       [4, 6, 8]], dtype=int32)>

In [16]:
tf.random.normal(shape=(2,2),mean=0,stddev=1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.7480518 ,  1.3964913 ],
       [ 0.30054957,  0.29612586]], dtype=float32)>

In [15]:
tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 4],
       [1, 3]], dtype=int32)>

In [17]:
a=tf.Variable(23)

In [18]:
a

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=23>

In [19]:
tensor = tf.Variable([ [ [10., 11., 12.], [13., 14., 15.] ], [ [16., 17., 18.], [19., 20., 21.] ] ]) # tensor variable
print(tensor.shape)

(2, 2, 3)


In [20]:
tensor1 = tf.reshape(tensor,[2,6])

In [21]:
tensor1

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21.]], dtype=float32)>

In [22]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[10., 11., 12.],
        [13., 14., 15.]],

       [[16., 17., 18.],
        [19., 20., 21.]]], dtype=float32)>

In [23]:
tensor1.numpy()

array([[10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21.]], dtype=float32)