<a href="https://colab.research.google.com/github/Pepcoders/Data-Science-March/blob/main/Numpy/Numpy_class_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Why Numpy

## 1. Faster than list/array

In [ ]:
l = [1] * 10000
print(len(l))

10000


In [ ]:
import numpy as np
arr = np.ones(1000, dtype='uint8')
len(arr)

1000

In [ ]:
%timeit sum(l)

10000 loops, best of 5: 70.1 µs per loop


In [ ]:
%timeit arr.sum()

The slowest run took 35.67 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 2.81 µs per loop


## 2. Fixed Type - No Type Checking

In [ ]:
l = [10, 20.5, "hello"]

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


In [ ]:
arr = np.array([10.5,2,3,4,5])
print(arr)
print(arr.dtype)

[10.5  2.   3.   4.   5. ]
float64


In [ ]:
arr = np.array([1,"20",3,4,5])
print(arr)
print(arr.dtype)

['1' '20' '3' '4' '5']
<U21


## 3. Less memory

In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [ ]:
arr = np.array([1, 2, 3, 4], dtype='uint16')
print(arr.dtype)

uint16


In [ ]:
arr = np.array([1, 2, 3, 4], dtype='int8')
print(arr.dtype)

int8


### size of list = size + object type + object value + referance count

## 4. Continuous Memory block

# Creating Scratch



*   ones
*   zeros
*   arange

In [ ]:
np.ones(9, dtype='int32')

array([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [ ]:
np.zeros((5, 2), dtype='int32')

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [ ]:
np.arange(9, 2, -2)

array([9, 7, 5, 3])

In [ ]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.ones((2,3,4)).shape

(2, 3, 4)

# Slicing

same as of python  [start: end: step]

numpy slicing is shallow copy
python does deep copy

In [ ]:
ar = np.arange(3, 20, 3)
ar

array([ 3,  6,  9, 12, 15, 18])

In [ ]:
ar[2: 4]

array([ 9, 12])

In [ ]:
l = [1,2,3,4]
l2 = l[1:3]
print(l)
print(l2)
l2[0] = 1000
print(l)
print(l2)

[1, 2, 3, 4]
[2, 3]
[1, 2, 3, 4]
[1000, 3]


In [ ]:
ar = np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ar = np.arange(10)
ar2 = ar[2:5]
print(ar)
print(ar2)
ar2[0] = 1000
print(ar)
print(ar2)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[   0    1 1000    3    4    5    6    7    8    9]
[1000    3    4]


In [ ]:
ar = np.arange(10)
ar2 = ar[2:5].copy()
print(ar)
print(ar2)
ar2[0] = 1000
print(ar)
print(ar2)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[1000    3    4]


# 2D Array

[start, end, step]

In [ ]:
ar = np.array([
          [1,2,3],
          [4,5,6],
          [7,8,9],
          [10,11,12]
])

In [ ]:
ar.ndim

2

In [ ]:
ar.shape

(4, 3)

In [ ]:
ar.size

12

In [ ]:
ar[1][0]

4

In [ ]:
ar[1, 0]

4

In [ ]:
ar

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
ar[1:3, 0:2]

array([[4, 5],
       [7, 8]])

In [ ]:
ar[::-1, ::-1]

array([[12, 11, 10],
       [ 9,  8,  7],
       [ 6,  5,  4],
       [ 3,  2,  1]])

In [ ]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.ones((2,3,4))[0, 1, 2]

1.0

#Operators

+
-
*
/
%
<
>
<=
>=

In [ ]:
print(a)
print(b)

[1 0 2 3]
[0 1 3 2]


In [ ]:
print(a + b)
print(a - b)
print(a * b)
print(a % b)
print(a / b)

[1 1 5 5]
[ 1 -1 -1  1]
[0 0 6 6]
[0 0 2 1]
[       inf 0.         0.66666667 1.5       ]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in remainder
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """


In [ ]:
print(a < b)
print(a > b)
print(a <= b)
print(a >= b)

[False  True  True False]
[ True False False  True]
[False  True  True False]
[ True False False  True]
